# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = HelloApp
DESTDIR = ./x64/Debug
INCLUDEPATH = ./x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(HelloApp.pri)
TRANSLATIONS += helloapp_zh.ts
win32:RC_FILE = HelloApp.rc
